Conventional/mysite/blog/urls.py
#coding: utf-8
from django.conf.urls import url
from blog.views import PostListView, PostDetailView,PostCreateView

urlpatterns = [
    url(r'^$', PostListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', PostDetailView.as_view(),name='detail'),
    url(r'^create/$', PostCreateView.as_view(),name='create'),
]

Conventional/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/blog/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]

# MEDIA
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Conventional/mysite/blog/models.py
#coding: utf-8
from django.db import models
#from django.contrib.sites.models import Site

class Category(models.Model):
    '''

    '''
    title = models.CharField(max_length=256, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=225)
    content = models.TextField(max_length=10000)
    published = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "{} ({})".format(self.title,'Published' if self.published else 'Not published')

    @models.permalink
    def get_absolute_url(self):
        return ('blog:detail', [self.pk])

Conventional/mysite/blog/views.py
#from django.shortcuts import render
from blog.models import Post
from django.views.generic import ListView, DetailView, CreateView


class PostListView(ListView):
    model = Post
    # template_name = "blog/post_list"
    # queryset = Post.objects.all()
    queryset = Post.objects.all().order_by('-modified_date')


class PostDetailView(DetailView):
    # template_name = "blog/post_detail"
    model = Post

class PostCreateView(CreateView):
    # template_name = "blog/post_form"
    model = Post
    fields = '__all__'

Conventional/mysite/blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>MyBlog</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {
                padding-top: 20px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
    </head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">My Blog</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'blog:list'%}">All Posts</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More... <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'blog:create'%}">New</a></li>
            </ul>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="container">
     {% block content %}Empty page{% endblock %}
</div> <!-- container -->

</body>

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</html>

Conventional/mysite/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h1 class="panel-title">{{ post.title }}</h1>
    </div>
    <div class="panel-body">
        <p>{{ post.content }}</p>
        <span class="label label-default">{{ post.category }}</span>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-right">
            {{ post.modified_date }}
        </div>
    </div>
</div>
<a href="{% url 'blog:list'%}" class="btn btn-primary" role="button">
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Back to post list...</a>

{% endblock %}

Conventional/mysite/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}

<!-- enctype="multipart/form-data" is for image upload -->
<form action="{% url 'blog:create'%}" class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
        <button class="btn btn-default" onclick="window.location='{% url 'blog:list'%}';return false;">Cancel</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

{% endblock %}

Conventional/mysite/blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    {% for post in object_list %}
      {% if post.published %}
        <div class="panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title">{{ post.title }}</h1>
            </div>
            <div class="panel-body">
                <p>{{ post.content |truncatechars:127 }}</p>
                <p><a href="{{ post.get_absolute_url }}">Read more...</a></p>
                <span class="label label-default">{{ post.category }}</span>
            </div>
            <div class="panel-footer clearfix">
                <div class="pull-right">
                  {{ post.modified_date }}
                </div>
            </div>
        </div>
      {% endif %}
    {% empty %}
    <p>No Posts!!</p>
    {% endfor %}

{% endblock %}